<%@ page language="java" contentType="text/html; charset=ISO-8859-1"
    pageEncoding="ISO-8859-1" import="com.cs336.pkg.*"%>
<%@ page import="java.io.*,java.util.*,java.sql.*"%>
<%@ page import="javax.servlet.http.*,javax.servlet.*" %>


<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta charset="UTF-8">
<link href="SalesReport.css" rel="stylesheet">
</head>
<body>

<br>
    <div class="nav-1">

        <div class="title2">
                    </div>

        <a href="../LandingPage.jsp" class="title" style = "text-decoration: none;">MASM</a>


        <div class="title2">

        </div>

    </div>











        <div class = "nav-2">

            <div class = "op6"></div>
            <div class="op7">
        <a href="AdminSuccess.jsp">Admin</a>
    </div>

            <div class = "op8"></div>
            <div class = "op9"></div>



        </div>
        <div class = "nav-3">
<div class = "op8">Produce a summary listing of revenue generated by a particular flight, airline, or 
        customer 
 </div>

    </div>

        <div class = "nav-4">

 <div class="box10">
    <div class="heading">Summaries</div>

    <form action="Summaries.jsp" method="POST">
        <br>Enter name exact: FlightNumber ex: 124325
        <br><input type="text" class = "flightnumber" name="flightNumber" placeholder="Enter Flight Number"> 
        <input class = "columnhead" type="submit" value="Retrieve" >
        <br>
        <br>
    </form>
    


    <% 
    if (session.getAttribute("user") == null) { %>
        You are not logged in<br/>
        <a href="AdminLogin.jsp">Please Login</a>
    <% } else { %>
        <%= session.getAttribute("user") %>

        <div class="table">

            <div class="column1">
                <div class="columnhead">Reservation by Flight Number</div>
                
                <% 
                ApplicationDB db = new ApplicationDB();
                Connection con = db.getConnection(db.getTravelDB());
                PreparedStatement pstmt = con.prepareStatement("SELECT FlightNumber, username, TicketNumber, FlightDuration, PurchaseDate, DepartureLocation, Destination, TotalPrice, Class FROM Ticket WHERE FlightNumber = ?");
                pstmt.setString(1, request.getParameter("flightNumber"));
                ResultSet rs1 = pstmt.executeQuery();

                while (rs1.next()) {
                    out.println("<br>");
                    out.println("Flight Number: " + rs1.getString("FlightNumber"));
                    out.println("<br>");
                    out.println("Account Number: " + rs1.getString("username"));
                    //out.println("<br>");
                    //out.println("Ticket Number: " + rs1.getString("TicketNumber"));
                    //out.println("<br>");
                    //out.println("Flight Duration: " + rs1.getString("FlightDuration"));
                    out.println("<br>");
                    out.println("Date: " + rs1.getString("PurchaseDate"));
                    out.println("<br>");
                    out.println("Depart: " + rs1.getString("DepartureLocation"));
                    out.println("<br>");
                    out.println("Landing: " + rs1.getString("Destination"));
                    out.println("<br>");
                    //out.println("Total Price: " + rs1.getString("TotalPrice"));
                    out.println("<br>");
                    //out.println("Class: " + rs1.getString("Class"));
                    out.println("<br>");}
%>
            </div>










            
            
            
            
            
            
          <%--
            
            
            <div class = "column2">
         <div class = "columnhead">Customer Name</div>
        <% 
        rs1 = stmt.executeQuery("SELECT PassengerName, SUM(TotalPrice) AS total_spent " +
                "FROM Ticket " +
                "GROUP BY PassengerName " +
                "ORDER BY total_spent DESC");

while (rs1.next()) {
String passengerName = rs1.getString("PassengerName");
double totalSpent = rs1.getDouble("total_spent");

out.println("<br>");
out.println(passengerName);
out.println("<br>");
out.println("Total Spent: $" + totalSpent);
out.println("<br>");
}

                        %>
            </div>
            
            

            
            
            
            <div class = "column1">
         <div class = "columnhead">Flight Duration</div>
        <% 
                   
                    rs1 = stmt.executeQuery("select FlightDuration as total_revenue from Ticket where extract(month from PurchaseDate) = '" + month + "' ");

                   
                    

                    while (rs1.next()) {
                    	out.println("<br>");
                        out.println(rs2.getString("total_revenue"));
                        out.println("<br>");
                    }

                    
                %>
            </div>
            
            
            --%>
            
            
            
            
            
            
            
            
            
        </div>

       
    <% } %>
</div>
      
      
      
      </div> 
      
      
          </div>


        </div>







</body>
</html>